const currencies = [
{currency:"AED", name:"UAE Dirham"},	
{currency:"AFN", name:"Afghan Afghani"},
{currency:"ALL", name:"Albanian Lek"},	
{currency:"AMD", name:"Armenian Dram"},
{currency:"ANG", name:"Netherlands Antillean Gulden"},	
{currency:"AOA", name:"Angolan Kwanza"},
{currency:"ARS", name:"Argentine Peso"},	
{currency:"AUD", name:"Australian Dollar"},
{currency:"AWG", name:"Aruban Florin"},	
{currency:"AZN", name:"Azerbaijani Manat"},
{currency:"BAM", name:"Bosnia And Herzegovina Konvertibilna Marka"},	
{currency:"BBD", name:"Barbadian Dollar"},
{currency:"BDT", name:"Bangladeshi Taka"},	
{currency:"BGN", name:"Bulgarian Lev"},
{currency:"BHD", name:"Bahraini Dinar"},	
{currency:"BIF", name:"Burundi Franc"},
{currency:"BMD", name:"Bermudan Dollar"},	
{currency:"BND", name:"Brunei Dollar"},
{currency:"BOB", name:"Bolivian Boliviano"},	
{currency:"BRL", name:"Brazilian Real"},
{currency:"BSD", name:"Bahamian Dollar"},	
{currency:"BTC", name:"Bitcoin"},
{currency:"BTN", name:"Bhutanese Ngultrum"},	
{currency:"BWP", name:"Botswana Pula"},
{currency:"BYN", name:"New Belarusian Ruble"},	
{currency:"BYR", name:"Belarusian Ruble"},
{currency:"BZD", name:"Belize Dollar"},	
{currency:"CAD", name:"Canadian Dollar"},
{currency:"CDF", name:"Congolese Franc"},	
{currency:"CHF", name:"Swiss Franc"},
{currency:"CLF", name:"Chilean Unit Of Account"},	
{currency:"CLP", name:"Chilean Peso"},
{currency:"CNY", name:"Chinese Yuan"},	
{currency:"COP", name:"Colombian Peso"},
{currency:"CRC", name:"Costa Rican Colon"},	
{currency:"CUC", name:"Cuban Convertible Peso"},
{currency:"CUP", name:"Cuban Peso"},	
{currency:"CVE", name:"Cape Verdean Escudo"},
{currency:"CZK", name:"Czech Koruna"},	
{currency:"DJF", name:"Djiboutian Franc"},
{currency:"DKK", name:"Danish Krone"},	
{currency:"DOP", name:"Dominican Peso"},
{currency:"DZD", name:"Algerian Dinar"},	
{currency:"EGP", name:"Egyptian Pound"},
{currency:"ERN", name:"Eritrean Nakfa"},	
{currency:"ETB", name:"Ethiopian Birr"},
{currency:"EUR", name:"Euro"},	
{currency:"FJD", name:"Fijian Dollar"},
{currency:"FKP", name:"Falkland Islands Pound"},	
{currency:"GBP", name:"British Pound"},
{currency:"GEL", name:"Georgian Lari"},	
{currency:"GGP", name:"Guernsey Pound"},
{currency:"GHS", name:"Ghanaian Cedi"},	
{currency:"GIP", name:"Gibraltar Pound"},
{currency:"GMD", name:"Gambian Dalasi"},	
{currency:"GNF", name:"Guinean Franc"},
{currency:"GTQ", name:"Guatemalan Quetzal"},	
{currency:"GYD", name:"Guyanese Dollar"},
{currency:"HKD", name:"Hong Kong Dollar"},	
{currency:"HNL", name:"Honduran Lempira"},
{currency:"HRK", name:"Croatian Kuna"},	
{currency:"HTG", name:"Haitian Gourde"},
{currency:"HUF", name:"Hungarian Forint"},	
{currency:"IDR", name:"Indonesian Rupiah"},
{currency:"ILS", name:"Israeli New Sheqel"},	
{currency:"IMP", name:"Manx pound"},
{currency:"INR", name:"Indian Rupee"},	
{currency:"IQD", name:"Iraqi Dinar"},
{currency:"IRR", name:"Iranian Rial"},	
{currency:"ISK", name:"Icelandic Kr\xc3\xb3na"},
{currency:"JEP", name:"Jersey Pound"},	
{currency:"JMD", name:"Jamaican Dollar"},
{currency:"JOD", name:"Jordanian Dinar"},	
{currency:"JPY", name:"Japanese Yen"},
{currency:"KES", name:"Kenyan Shilling"},	
{currency:"KGS", name:"Kyrgyzstani Som"},
{currency:"KHR", name:"Cambodian Riel"},	
{currency:"KMF", name:"Comorian Franc"},
{currency:"KPW", name:"North Korean Won"},	
{currency:"KRW", name:"South Korean Won"},
{currency:"KWD", name:"Kuwaiti Dinar"},	
{currency:"KYD", name:"Cayman Islands Dollar"},
{currency:"KZT", name:"Kazakhstani Tenge"},	
{currency:"LAK", name:"Lao Kip"},
{currency:"LBP", name:"Lebanese Lira"},	
{currency:"LKR", name:"Sri Lankan Rupee"},
{currency:"LRD", name:"Liberian Dollar"},	
{currency:"LSL", name:"Lesotho Loti"},
{currency:"LVL", name:"Latvian Lats"},	
{currency:"LYD", name:"Libyan Dinar"},
{currency:"MAD", name:"Moroccan Dirham"},	
{currency:"MDL", name:"Moldovan Leu"},
{currency:"MGA", name:"Malagasy Ariary"},	
{currency:"MKD", name:"Macedonian Denar"},
{currency:"MMK", name:"Myanma Kyat"},	
{currency:"MNT", name:"Mongolian Tugrik"},
{currency:"MOP", name:"Macanese Pataca"},	
{currency:"MRO", name:"Mauritanian Ouguiya"},
{currency:"MUR", name:"Mauritian Rupee"},	
{currency:"MVR", name:"Maldivian Rufiyaa"},
{currency:"MWK", name:"Malawian Kwacha"},	
{currency:"MXN", name:"Mexican Peso"},
{currency:"MYR", name:"Malaysian Ringgit"},	
{currency:"MZN", name:"Mozambican Metical"},
{currency:"NAD", name:"Namibian Dollar"},	
{currency:"NGN", name:"Nigerian Naira"},
{currency:"NIO", name:"Nicaraguan Cordoba"},	
{currency:"NOK", name:"Norwegian Krone"},
{currency:"NPR", name:"Nepalese Rupee"},	
{currency:"NZD", name:"New Zealand Dollar"},
{currency:"OMR", name:"Omani Rial"},	
{currency:"PAB", name:"Panamanian Balboa"},
{currency:"PEN", name:"Peruvian Nuevo Sol"},	
{currency:"PGK", name:"Papua New Guinean Kina"},
{currency:"PHP", name:"Philippine Peso"},	
{currency:"PKR", name:"Pakistani Rupee"},
{currency:"PLN", name:"Polish Zloty"},	
{currency:"PYG", name:"Paraguayan Guarani"},
{currency:"QAR", name:"Qatari Riyal"},	
{currency:"RON", name:"Romanian Leu"},
{currency:"RSD", name:"Serbian Dinar"},	
{currency:"RUB", name:"Russian Ruble"},
{currency:"RWF", name:"Rwandan Franc"},	
{currency:"SAR", name:"Saudi Riyal"},
{currency:"SBD", name:"Solomon Islands Dollar"},	
{currency:"SCR", name:"Seychellois Rupee"},
{currency:"SDG", name:"Sudanese Pound"},	
{currency:"SEK", name:"Swedish Krona"},
{currency:"SGD", name:"Singapore Dollar"},	
{currency:"SHP", name:"Saint Helena Pound"},
{currency:"SLL", name:"Sierra Leonean Leone"},	
{currency:"SOS", name:"Somali Shilling"},
{currency:"SRD", name:"Surinamese Dollar"},	
{currency:"STD", name:"Sao Tome And Principe Dobra"},
{currency:"SVC", name:"Salvadoran Col\xc3\xb3n"},	
{currency:"SYP", name:"Syrian Pound"},
{currency:"SZL", name:"Swazi Lilangeni"},	
{currency:"THB", name:"Thai Baht"},
{currency:"TJS", name:"Tajikistani Somoni"},	
{currency:"TMT", name:"Turkmenistan Manat"},
{currency:"TND", name:"Tunisian Dinar"},	
{currency:"TOP", name:"Paanga"},
{currency:"TRY", name:"Turkish New Lira"},	
{currency:"TTD", name:"Trinidad and Tobago Dollar"},
{currency:"TWD", name:"New Taiwan Dollar"},	
{currency:"TZS", name:"Tanzanian Shilling"},
{currency:"UAH", name:"Ukrainian Hryvnia"},	
{currency:"UGX", name:"Ugandan Shilling"},
{currency:"USD", name:"United States Dollar"},	
{currency:"UYU", name:"Uruguayan Peso"},
{currency:"UZS", name:"Uzbekistani Som"},	
{currency:"VEF", name:"Venezuelan Bolivar"},
{currency:"VND", name:"Vietnamese Dong"},	
{currency:"VUV", name:"Vanuatu Vatu"},
{currency:"WST", name:"Samoan Tala"},	
{currency:"XAF", name:"Central African CFA Franc"},
{currency:"XAG", name:"Silver (troy ounce)"},	
{currency:"XCD", name:"East Caribbean Dollar"},
{currency:"XDR", name:"Special Drawing Rights"},	
{currency:"XOF", name:"West African CFA Franc"},
{currency:"XPF", name:"CFP Franc"},	
{currency:"YER", name:"Yemeni Rial"},
{currency:"ZAR", name:"South African Rand	"},
{currency:"ZMK", name:"Old Zambian Kwacha"},
{currency:"ZMW", name:"Zambian Kwacha"},
{currency:"ZWL", name:"Zimbabwean Dollar"}
]

export default currencies